copy_file 'lib/tasks/auto_annotate_models.rake'
copy_file 'lib/tasks/auto_generate_diagram.rake'
copy_file 'lib/tasks/coverage.rake'
copy_file 'lib/generators/api_controller_generator.rb'
copy_file 'lib/generators/templates/controller.rb.erb'
copy_file 'lib/generators/templates/doc.rb.erb'
copy_file 'lib/generators/templates/spec.rb.erb'
